#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Fake XDG exports, for uniformity (needed by, e.g., `man-to-*` scripts 
#                                   in `bin`)

export XDG_CACHE_HOME="$HOME/Library/Caches/"
