#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Disabling telemetry capabilities in various apps
# See https://github.com/beatcracker/toptout

export HOMEBREW_NO_ANALYTICS=1
export AZURE_CORE_COLLECT_TELEMETRY=0

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Fake XDG exports, for uniformity (needed by, e.g., `man-to-*` scripts 
#                                   in `bin`)

export XDG_CACHE_HOME="$HOME/Library/Caches/"
