#!/bin/bash

# Readline library configuration options.
# http://ss64.com/bash/syntax-inputrc.html

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Disable beeping and window flashing.

set bell-style none

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Use case-insensitive TAB autocompletion.

set completion-ignore-case on

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Auto list TAB completions.

set show-all-if-ambiguous on

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Add a slash to completed symlinks that are directories

set mark-symlinked-directories on

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Append file type markers when listing possible completions

set visible-stats on

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Signal whether parentheses match

set blink-matching-paren on

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# For example, "cd ~/src/mo[z]il" => "cd ~/src/mozilla", not "mozillail"
# (This is supported by the Readline used by Bash 4.)

set skip-completed-text on

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# If there are multiple matches for completion,
# make Shift+Tab cycle through them inline.

"\e[Z": menu-complete

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Perform partial completion on the first Shift+Tab press, and
# only start cycling full results on the second Shift+Tab press.

set menu-complete-display-prefix on
