#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Always ask for confirmation

alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Allow aliases to be `sudo`ed
# https://stackoverflow.com/questions/37209913/how-does-alias-sudo-sudo-work

alias sudo='sudo '

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias g="git"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ll="ls -l"
alias map="xargs -n1"
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias t="tmux"
alias trim='cut -c -`tput cols`'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias lsync="rsync -avh --progress"
alias nsync="rsync -avzh --progress"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias zip0="zip -0vo"
alias zip1="zip -1vo"
alias zip9="zip -9vo"
alias zipforget="zip -m9voT"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Duplicates `delete-files` in `bash_functions`

alias rmdsstore="find . -type f -name '*.DS_Store' -ls -delete"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases.

. "aliases/$OS/bash_aliases"
